[tool.poetry]
name = "lighthearted"
version = "0.1.0"
description = "Python mental health AI application."
readme = "README.md"
authors = [
  "Blake Hamm <blake.j.hamm@gmail.com>"
]
maintainers = [
  "Blake Hamm <blake.j.hamm@gmail.com>"
]
license = "BSD license"
packages = [{include = "lighthearted", from = "src"}]

[tool.poetry.dependencies]
python = "^3.12"
python-dotenv = "^1.0.1"
dspy = "^2.5.43"
google-cloud-aiplatform = "^1.77.0"
streamlit = "^1.41.1"

[tool.poetry.group.dev.dependencies]
cookiecutter = "^2.6.0"
cruft = "^2.15.0"
pytest = "^8.3.2"
pytest-cov = "^5.0.0"
coverage = "^7.6.1"
ruff = "^0.5.7"
pre-commit = "^3.8.0"
ipykernel = "^6.29.5"
notebook = "^7.3.2"
matplotlib = "^3.10.0"
pandas = "^2.2.3"
seaborn = "^0.13.2"
ipywidgets = "^8.1.5"


[tool.ruff] # Linting rules
select = ["I", "F", "E", "W", "N", "D", "ANN", "B", "A", "T20", "PYI", "Q", "RET", "ARG", "PTH", "PL", "PT"]


[tool.pytest.ini_options]
adopts = "-s"
testpaths = ["tests"]

[tool.coverage] # Coverage config
source = [
  "src",
  "tests",
  "notebooks",
]

[tool.coverage.run]
command_line = "-m pytest"
omit = ["*test*", "*__init__*"]

# Always include branch coverage
branch = true

[tool.coverage.report]
fail_under = 80
ignore_errors = true
show_missing = true


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[virtualenvs]
in-project = true
